version: "3.8"

services:
  raft-server-1:
    build:
      context: .
      dockerfile: server.Dockerfile
    container_name: raft-server-1
    environment:
      - SERVER_ID=1
      - SERVER_PORT=5000
    ports:
      - 5000:5000
    networks:
      - raft-network

  raft-server-2:
    build:
      context: .
      dockerfile: server.Dockerfile
    container_name: raft-server-2
    environment:
      - SERVER_ID=2
      - SERVER_PORT=5000
    ports:
      - 5001:5000
    networks:
      - raft-network

  raft-server-3:
    build:
      context: .
      dockerfile: server.Dockerfile
    container_name: raft-server-3
    environment:
      - SERVER_ID=3
      - SERVER_PORT=5000
    ports:
      - 5002:5000
    networks:
      - raft-network

  raft-server-4:
    build:
      context: .
      dockerfile: server.Dockerfile
    container_name: raft-server-4
    environment:
      - SERVER_ID=4
      - SERVER_PORT=5000
    ports:
      - 5003:5000
    networks:
      - raft-network

  raft-server-5:
    build:
      context: .
      dockerfile: server.Dockerfile
    container_name: raft-server-5
    environment:
      - SERVER_ID=5
      - SERVER_PORT=5000
    ports:
      - 5004:5000
    networks:
      - raft-network

  tests:
    build:
      context: .
      dockerfile: test.Dockerfile
    container_name: raft-tests
    networks:
      - raft-network


networks:
  raft-network:
    driver: bridge